import { MeaningMatchQuestion } from "../../types/content";
import { A1_CORE_VOCABULARY } from "../vocabulary/a1CoreVocabulary";

export const a1MeaningMatchQuestions: MeaningMatchQuestion[] = [
  {
    id: "a1-mm-01",
    mode: "MEANING_MATCH",
    level: "A1",
    topic: "Sıfatlar",
    word: "quiet",
    meaning: "sessiz",
    wrongOptions: ["hızlı", "mutlu"],
    xp: 10,
    difficulty: 1,
    phonetic: "/ˈkwaɪ.ət/",
    partOfSpeech: "adjective",
    exampleSentence: "The garden is very quiet in the morning.",
    exampleTranslation: "Bahçe sabahları çok sessizdir.",
    contextNote: "Gürültü ve sesin bulunmadığı sakin durumları niteler.",
    pronunciation: "quiet",
    hint: "Gürültüsüz, sakin ve huzurlu bir durum.",
    prompt: "quiet",
    answer: "sessiz",
    options: ["sessiz", "hızlı", "mutlu"],
  },
  {
    id: "a1-mm-02",
    mode: "MEANING_MATCH",
    level: "A1",
    topic: "Bahçe & Doğa",
    word: "leaf",
    meaning: "yaprak",
    wrongOptions: ["ağaç", "toprak"],
    xp: 10,
    difficulty: 1,
    phonetic: "/liːf/",
    partOfSpeech: "noun",
    exampleSentence: "A tiny green leaf sprouted from the seed.",
    exampleTranslation: "Tohumdan küçük yeşil bir yaprak filizlendi.",
    contextNote: "Bitkilerin fotosentez yapan yeşil organıdır.",
    pronunciation: "leaf",
    hint: "Bitkilerin yeşil renkli nefes alan parçası.",
    prompt: "leaf",
    answer: "yaprak",
    options: ["yaprak", "ağaç", "toprak"],
  },
  {
    id: "a1-mm-03",
    mode: "MEANING_MATCH",
    level: "A1",
    topic: "Günlük Yaşam",
    word: "water",
    meaning: "su",
    wrongOptions: ["ekmek", "kahve"],
    xp: 10,
    difficulty: 1,
    phonetic: "/ˈwɔː.tər/",
    partOfSpeech: "noun",
    exampleSentence: "Plants need fresh water and sunlight to grow.",
    exampleTranslation: "Bitkilerin büyümek için taze suya ve güneş ışığına ihtiyacı vardır.",
    contextNote: "Tüm canlıların yaşam kaynağı olan berrak sıvı.",
    pronunciation: "water",
    hint: "Bitkilerin ve canlıların yaşam kaynağı.",
    prompt: "water",
    answer: "su",
    options: ["su", "ekmek", "kahve"],
  },
  {
    id: "a1-mm-04",
    mode: "MEANING_MATCH",
    level: "A1",
    topic: "Duygular",
    word: "happy",
    meaning: "mutlu",
    wrongOptions: ["üzgün", "yorgun"],
    xp: 10,
    difficulty: 1,
    phonetic: "/ˈhæp.i/",
    partOfSpeech: "adjective",
    exampleSentence: "Sprig feels happy in the blooming garden.",
    exampleTranslation: "Sprig çiçek açan bahçede mutlu hissediyor.",
    contextNote: "Sevinç, neşe ve memnuniyet belirten temel sıfat.",
    pronunciation: "happy",
    hint: "Sevinçli ve neşeli hissetme hali.",
    prompt: "happy",
    answer: "mutlu",
    options: ["mutlu", "üzgün", "yorgun"],
  },
  {
    id: "a1-mm-05",
    mode: "MEANING_MATCH",
    level: "A1",
    topic: "Zaman & Gün",
    word: "morning",
    meaning: "sabah",
    wrongOptions: ["gece", "öğle"],
    xp: 10,
    difficulty: 1,
    phonetic: "/ˈmɔː.nɪŋ/",
    partOfSpeech: "noun",
    exampleSentence: "Early morning is the best time for learning.",
    exampleTranslation: "Sabahın erken saatleri öğrenmek için en iyi zamandır.",
    contextNote: "Günün güneş doğumuyla başlayan ilk periyodu.",
    pronunciation: "morning",
    hint: "Günün güneşle başlayan ilk saatleri.",
    prompt: "morning",
    answer: "sabah",
    options: ["sabah", "gece", "öğle"],
  },
  {
    id: "a1-mm-06",
    mode: "MEANING_MATCH",
    level: "A1",
    topic: "Renkler & Doğa",
    word: "green",
    meaning: "yeşil",
    wrongOptions: ["kırmızı", "sarı"],
    xp: 10,
    difficulty: 1,
    phonetic: "/ɡriːn/",
    partOfSpeech: "adjective",
    exampleSentence: "The grass in the meadow is vibrant green.",
    exampleTranslation: "Çayırdaki çimenler canlı bir yeşildir.",
    contextNote: "Doğayı, tazeliği ve bitkileri temsil eden ana renk.",
    pronunciation: "green",
    hint: "Çimenlerin ve yaprakların taze rengi.",
    prompt: "green",
    answer: "yeşil",
    options: ["yeşil", "kırmızı", "sarı"],
  },
  {
    id: "a1-mm-07",
    mode: "MEANING_MATCH",
    level: "A1",
    topic: "Ev & Bahçe",
    word: "seed",
    meaning: "tohum",
    wrongOptions: ["çiçek", "dal"],
    xp: 10,
    difficulty: 1,
    phonetic: "/siːd/",
    partOfSpeech: "noun",
    exampleSentence: "Plant a small seed and watch it rise.",
    exampleTranslation: "Küçük bir tohum ek ve büyümesini izle.",
    contextNote: "Toprağa ekildiğinde yeni bir bitki oluşturan çekirdek.",
    pronunciation: "seed",
    hint: "Toprağa ekildiğinde yeni bir bitki oluşturan küçük tanecik.",
    prompt: "seed",
    answer: "tohum",
    options: ["tohum", "çiçek", "dal"],
  },
];

const curatedWords = new Set(a1MeaningMatchQuestions.map((question) => question.word));
const generatedA1Questions: MeaningMatchQuestion[] = A1_CORE_VOCABULARY
  .filter((entry) => !curatedWords.has(entry.word))
  .map((entry, index, pool) => {
    const wrongOptions = Array.from(new Set(
      [...pool.slice(index + 1), ...pool.slice(0, index)]
        .map((candidate) => candidate.meaningTr)
        .filter((meaning) => meaning !== entry.meaningTr)
    )).slice(0, 2);
    return { id: `a1-core-${entry.word.replace(/[^a-z]/g, "-")}`, mode: "MEANING_MATCH", level: "A1", topic: entry.topic, word: entry.word, meaning: entry.meaningTr, wrongOptions, xp: 10, difficulty: 1, partOfSpeech: entry.partOfSpeech, exampleSentence: `Learn and use the word “${entry.word}” in a simple sentence.`, exampleTranslation: `“${entry.word}” kelimesini basit bir cümlede öğren ve kullan.`, contextNote: `${entry.topic} konusu için güvenli A1 çekirdek kelimesi.`, pronunciation: entry.word, hint: `${entry.topic} konusundaki temel kelimeyi seç.`, prompt: entry.word, answer: entry.meaningTr, options: [entry.meaningTr, ...wrongOptions] };
  });

const A1_UNIT_SIZE = 30;

// Publishing metadata is stamped here rather than left blank, so every question
// carries the unit and ordering the rest of the app reads.
export const a1Questions: MeaningMatchQuestion[] = [
  ...a1MeaningMatchQuestions,
  ...generatedA1Questions,
].map((question, index) => ({
  ...question,
  unitId: `a1-u${String(Math.floor(index / A1_UNIT_SIZE) + 1).padStart(2, "0")}`,
  order: index,
  status: "published" as const,
}));
