import { MeaningMatchQuestion } from "../../types/content";
import { a2GeneratedQuestions } from "./a2Generated";

export const a2MeaningMatchQuestions: MeaningMatchQuestion[] = [
  {
    id: "a2-mm-01",
    mode: "MEANING_MATCH",
    level: "A2",
    topic: "Doğa & Bitkiler",
    word: "blossom",
    meaning: "çiçek açmak",
    wrongOptions: ["solmak", "büyümek"],
    xp: 15,
    difficulty: 2,
    phonetic: "/ˈblɒs.əm/",
    partOfSpeech: "verb",
    exampleSentence: "Cherry trees blossom beautifully in spring.",
    exampleTranslation: "Kiraz ağaçları ilkbaharda harika çiçek açar.",
    contextNote: "Ağaçların veya bitkilerin çiçek üretme eylemi.",
    pronunciation: "blossom",
    hint: "Ağaçların baharda rengarenk çiçeklerle kaplanması.",
    prompt: "blossom",
    answer: "çiçek açmak",
    options: ["çiçek açmak", "solmak", "büyümek"],
  },
  {
    id: "a2-mm-02",
    mode: "MEANING_MATCH",
    level: "A2",
    topic: "Seyahat & Keşif",
    word: "journey",
    meaning: "yolculuk",
    wrongOptions: ["durak", "bilet"],
    xp: 15,
    difficulty: 2,
    phonetic: "/ˈdʒɜː.ni/",
    partOfSpeech: "noun",
    exampleSentence: "Language learning is an exciting journey.",
    exampleTranslation: "Dil öğrenmek heyecan verici bir yolculuktur.",
    contextNote: "Bir noktadan diğerine giden serüven veya seyahat.",
    pronunciation: "journey",
    hint: "Bir yerden başka bir yere yapılan seyahat.",
    prompt: "journey",
    answer: "yolculuk",
    options: ["yolculuk", "durak", "bilet"],
  },
  {
    id: "a2-mm-03",
    mode: "MEANING_MATCH",
    level: "A2",
    topic: "Sıfatlar & Duygular",
    word: "gentle",
    meaning: "nazik",
    wrongOptions: ["sert", "kaba"],
    xp: 15,
    difficulty: 2,
    phonetic: "/ˈdʒen.təl/",
    partOfSpeech: "adjective",
    exampleSentence: "A gentle breeze cooled the afternoon heat.",
    exampleTranslation: "Nazik bir esinti öğleden sonraki sıcağı serinletti.",
    contextNote: "Yumuşak, ılımlı ve kibar etkileri tanımlar.",
    pronunciation: "gentle",
    hint: "Yumuşak huylu, kibar ve incelikli davranış.",
    prompt: "gentle",
    answer: "nazik",
    options: ["nazik", "sert", "kaba"],
  },
  {
    id: "a2-mm-04",
    mode: "MEANING_MATCH",
    level: "A2",
    topic: "Çevre & Yaşam",
    word: "shelter",
    meaning: "barınak",
    wrongOptions: ["yol", "orman"],
    xp: 15,
    difficulty: 2,
    phonetic: "/ˈʃel.tər/",
    partOfSpeech: "noun",
    exampleSentence: "Birds find shelter among the thick branches.",
    exampleTranslation: "Kuşlar sık dalların arasında barınak bulur.",
    contextNote: "Hava koşullarından ve tehlikeden koruyan sığınak.",
    pronunciation: "shelter",
    hint: "Yağmurdan veya tehlikeden koruyan güvenli sığınak.",
    prompt: "shelter",
    answer: "barınak",
    options: ["barınak", "yol", "orman"],
  },
  {
    id: "a2-mm-05",
    mode: "MEANING_MATCH",
    level: "A2",
    topic: "Doğa & Çevre",
    word: "soil",
    meaning: "toprak",
    wrongOptions: ["kum", "taş"],
    xp: 15,
    difficulty: 2,
    phonetic: "/sɔɪl/",
    partOfSpeech: "noun",
    exampleSentence: "Rich soil provides essential nutrients for plants.",
    exampleTranslation: "Zengin toprak bitkiler için gerekli besinleri sağlar.",
    contextNote: "Bitkilerin kök saldığı verimli üst yeryüzü katmanı.",
    pronunciation: "soil",
    hint: "Bitkilerin kök salıp beslendiği verimli yeryüzü katmanı.",
    prompt: "soil",
    answer: "toprak",
    options: ["toprak", "kum", "taş"],
  },
];

const A2_UNIT_SIZE = 30;

// Same publishing-metadata pattern as a1.ts — every question carries the
// unit and ordering the rest of the app reads.
export const a2Questions: MeaningMatchQuestion[] = [
  ...a2MeaningMatchQuestions,
  ...a2GeneratedQuestions,
].map((question, index) => ({
  ...question,
  unitId: `a2-u${String(Math.floor(index / A2_UNIT_SIZE) + 1).padStart(2, "0")}`,
  order: index,
  status: "published" as const,
}));
