import { MeaningMatchQuestion } from "../../types/content";
import { computeDifficulty, computeXpReward } from "./difficulty";

/**
 * A2 core vocabulary expansion (Sprint 6 / roadmap Birim 1.1). Unlike the
 * original A1 generator, every row carries its own real, hand-written
 * example sentence from the start — there is no templated-sentence step to
 * later clean up.
 */
type PartOfSpeech = "noun" | "verb" | "adjective" | "adverb" | "phrase";
type Row = readonly [word: string, meaningTr: string, pos: PartOfSpeech, en: string, tr: string];

interface TopicBlock {
  topic: string;
  rows: Row[];
}

const TOPICS: TopicBlock[] = [
  {
    topic: "İş & Kariyer",
    rows: [
      ["job", "iş", "noun", "She found a new job last month.", "Geçen ay yeni bir iş buldu."],
      ["career", "kariyer", "noun", "He is building a career in medicine.", "Tıp alanında bir kariyer inşa ediyor."],
      ["office", "ofis", "noun", "Our office is downtown.", "Ofisimiz şehir merkezinde."],
      ["meeting", "toplantı", "noun", "The meeting starts at ten.", "Toplantı saat onda başlıyor."],
      ["boss", "patron", "noun", "My boss is very supportive.", "Patronum çok destekleyici."],
      ["colleague", "meslektaş", "noun", "I had lunch with a colleague.", "Bir meslektaşımla öğle yemeği yedim."],
      ["salary", "maaş", "noun", "The salary is paid monthly.", "Maaş aylık olarak ödenir."],
      ["interview", "mülakat", "noun", "She has a job interview tomorrow.", "Yarın bir iş görüşmesi var."],
      ["company", "şirket", "noun", "He works for a large company.", "Büyük bir şirkette çalışıyor."],
      ["project", "proje", "noun", "We finished the project on time.", "Projeyi zamanında bitirdik."],
      ["deadline", "son teslim tarihi", "noun", "The deadline is next Friday.", "Son teslim tarihi gelecek cuma."],
      ["report", "rapor", "noun", "Please send the report by email.", "Lütfen raporu e-posta ile gönder."],
      ["schedule", "program", "noun", "My schedule is full this week.", "Bu hafta programım dolu."],
      ["experience", "deneyim", "noun", "She has five years of experience.", "Beş yıllık deneyimi var." ],
      ["skill", "beceri", "noun", "Communication is an important skill.", "İletişim önemli bir beceridir."],
      ["degree", "diploma", "noun", "He earned a degree in engineering.", "Mühendislik diploması aldı."],
      ["apply", "başvurmak", "verb", "I applied for the position last week.", "Geçen hafta pozisyona başvurdum."],
      ["hire", "işe almak", "verb", "The company plans to hire more staff.", "Şirket daha fazla personel işe almayı planlıyor."],
      ["promote", "terfi ettirmek", "verb", "They promoted her to manager.", "Onu müdürlüğe terfi ettirdiler."],
      ["resign", "istifa etmek", "verb", "He decided to resign from his job.", "İşinden istifa etmeye karar verdi."],
      ["retire", "emekli olmak", "verb", "My father will retire next year.", "Babam gelecek yıl emekli olacak."],
      ["manager", "müdür", "noun", "The manager approved our request.", "Müdür isteğimizi onayladı."],
      ["employee", "çalışan", "noun", "Every employee gets health insurance.", "Her çalışan sağlık sigortası alır."],
      ["client", "müşteri", "noun", "We are meeting a client today.", "Bugün bir müşteriyle görüşüyoruz."],
      ["contract", "sözleşme", "noun", "Please sign the contract here.", "Lütfen sözleşmeyi buradan imzala."],
      ["business", "iş dünyası", "noun", "She started her own business.", "Kendi işini kurdu."],
      ["industry", "sektör", "noun", "He works in the tourism industry.", "Turizm sektöründe çalışıyor."],
      ["factory", "fabrika", "noun", "The factory produces furniture.", "Fabrika mobilya üretiyor."],
      ["department", "departman", "noun", "She works in the sales department.", "Satış departmanında çalışıyor."],
      ["task", "görev", "noun", "I completed all my tasks today.", "Bugün tüm görevlerimi tamamladım."],
      ["goal", "hedef", "noun", "Our goal is to finish by June.", "Hedefimiz haziranda bitirmek."],
      ["achievement", "başarı", "noun", "Winning the award was a great achievement.", "Ödülü kazanmak büyük bir başarıydı."],
      ["responsibility", "sorumluluk", "noun", "He takes his responsibilities seriously.", "Sorumluluklarını ciddiye alır."],
      ["professional", "profesyonel", "adjective", "She gave a very professional presentation.", "Çok profesyonel bir sunum yaptı."],
      ["promotion", "terfi", "noun", "He got a promotion this year.", "Bu yıl terfi aldı."],
      ["training", "eğitim", "noun", "New staff receive two weeks of training.", "Yeni personel iki hafta eğitim alır."],
      ["overtime", "mesai", "noun", "She worked overtime to finish the report.", "Raporu bitirmek için fazla mesai yaptı."],
    ],
  },
  {
    topic: "Seyahat",
    rows: [
      ["airport", "havaalanı", "noun", "We arrived at the airport early.", "Havaalanına erken vardık."],
      ["flight", "uçuş", "noun", "Our flight was delayed by an hour.", "Uçuşumuz bir saat gecikti."],
      ["passport", "pasaport", "noun", "Don't forget your passport.", "Pasaportunu unutma."],
      ["luggage", "bagaj", "noun", "My luggage didn't arrive.", "Bagajım gelmedi."],
      ["suitcase", "valiz", "noun", "She packed her suitcase quickly.", "Valizini hızlıca hazırladı."],
      ["hotel", "otel", "noun", "We booked a hotel near the beach.", "Sahile yakın bir otel ayırttık."],
      ["reservation", "rezervasyon", "noun", "I made a reservation for two.", "İki kişilik rezervasyon yaptırdım."],
      ["destination", "varış noktası", "noun", "Paris is our next destination.", "Paris bir sonraki varış noktamız."],
      ["tourist", "turist", "noun", "Many tourists visit this old town.", "Bu eski kasabayı birçok turist ziyaret ediyor."],
      ["guide", "rehber", "noun", "Our guide showed us the old city.", "Rehberimiz bize eski şehri gösterdi."],
      ["souvenir", "hediyelik eşya", "noun", "I bought a souvenir for my sister.", "Kız kardeşim için hediyelik eşya aldım."],
      ["border", "sınır", "noun", "We crossed the border by bus.", "Sınırı otobüsle geçtik."],
      ["customs", "gümrük", "noun", "We waited at customs for an hour.", "Gümrükte bir saat bekledik."],
      ["visa", "vize", "noun", "You need a visa to visit that country.", "O ülkeyi ziyaret etmek için vizeye ihtiyacın var."],
      ["departure", "kalkış", "noun", "The departure gate changed suddenly.", "Kalkış kapısı aniden değişti."],
      ["arrival", "varış", "noun", "Please check the arrival time.", "Lütfen varış saatini kontrol et."],
      ["delay", "gecikme", "noun", "There was a two-hour delay at the airport.", "Havaalanında iki saatlik gecikme oldu."],
      ["gate", "kapı", "noun", "Our gate number changed to twelve.", "Kapı numaramız on ikiye değişti."],
      ["currency", "para birimi", "noun", "I exchanged some currency at the airport.", "Havaalanında biraz para bozdurdum."],
      ["backpack", "sırt çantası", "noun", "He traveled with only a backpack.", "Sadece bir sırt çantasıyla seyahat etti."],
      ["camping", "kamp", "noun", "We went camping by the lake.", "Gölün kenarında kampa gittik."],
      ["tent", "çadır", "noun", "We set up the tent before sunset.", "Çadırı gün batımından önce kurduk."],
      ["beach", "plaj", "noun", "The beach was crowded this weekend.", "Bu hafta sonu plaj kalabalıktı."],
      ["island", "ada", "noun", "We took a boat to the island.", "Adaya tekneyle gittik."],
      ["abroad", "yurt dışında", "adverb", "She studied abroad for a year.", "Bir yıl yurt dışında okudu."],
      ["foreign", "yabancı", "adjective", "He speaks three foreign languages.", "Üç yabancı dil konuşuyor."],
      ["local", "yerel", "adjective", "We tried the local food.", "Yerel yemekleri denedik."],
      ["culture", "kültür", "noun", "I love learning about new cultures.", "Yeni kültürler hakkında bilgi edinmeyi severim."],
      ["tradition", "gelenek", "noun", "This festival is an old tradition.", "Bu festival eski bir gelenektir."],
      ["adventure", "macera", "noun", "The trip was a real adventure.", "Gezi gerçek bir maceraydı."],
      ["explore", "keşfetmek", "verb", "We explored the city on foot.", "Şehri yürüyerek keşfettik."],
      ["discover", "keşfetmek", "verb", "They discovered a hidden waterfall.", "Gizli bir şelale keşfettiler."],
      ["itinerary", "seyahat planı", "noun", "Our itinerary includes three cities.", "Seyahat planımız üç şehri içeriyor."],
      ["accommodation", "konaklama", "noun", "Accommodation is included in the price.", "Konaklama fiyata dahildir."],
      ["sightseeing", "gezip görme", "noun", "We spent the day sightseeing.", "Günü gezip görerek geçirdik."],
    ],
  },
  {
    topic: "Teknoloji",
    rows: [
      ["internet", "internet", "noun", "The internet is very slow today.", "İnternet bugün çok yavaş."],
      ["website", "web sitesi", "noun", "I found this recipe on a website.", "Bu tarifi bir web sitesinde buldum."],
      ["application", "uygulama", "noun", "This application helps you learn languages.", "Bu uygulama dil öğrenmene yardımcı olur."],
      ["password", "şifre", "noun", "Please choose a strong password.", "Lütfen güçlü bir şifre seç."],
      ["download", "indirmek", "verb", "I downloaded the file quickly.", "Dosyayı hızlıca indirdim."],
      ["upload", "yüklemek", "verb", "She uploaded the photos to the cloud.", "Fotoğrafları buluta yükledi."],
      ["wifi", "kablosuz internet", "noun", "The cafe has free wifi.", "Kafede ücretsiz kablosuz internet var."],
      ["network", "ağ", "noun", "The network was down this morning.", "Ağ bu sabah çalışmıyordu."],
      ["device", "cihaz", "noun", "Charge your device before the trip.", "Seyahatten önce cihazını şarj et."],
      ["screen", "ekran", "noun", "The screen is too bright.", "Ekran çok parlak."],
      ["keyboard", "klavye", "noun", "My keyboard stopped working.", "Klavyem çalışmayı bıraktı."],
      ["printer", "yazıcı", "noun", "The printer is out of paper.", "Yazıcının kağıdı bitti."],
      ["camera", "kamera", "noun", "This camera takes great photos.", "Bu kamera harika fotoğraflar çekiyor."],
      ["video", "video", "noun", "We watched a funny video together.", "Birlikte komik bir video izledik."],
      ["message", "mesaj", "noun", "I sent you a message yesterday.", "Sana dün bir mesaj gönderdim."],
      ["account", "hesap", "noun", "I forgot my account password.", "Hesap şifremi unuttum."],
      ["profile", "profil", "noun", "Update your profile picture.", "Profil fotoğrafını güncelle."],
      ["update", "güncelleme", "noun", "There is a new software update.", "Yeni bir yazılım güncellemesi var."],
      ["install", "yüklemek", "verb", "Please install the latest version.", "Lütfen en son sürümü yükle."],
      ["battery", "pil", "noun", "My phone battery is almost empty.", "Telefonumun pili neredeyse bitti."],
      ["charger", "şarj cihazı", "noun", "I forgot my charger at home.", "Şarj cihazımı evde unuttum."],
      ["signal", "sinyal", "noun", "There is no signal in the tunnel.", "Tünelde sinyal yok."],
      ["connection", "bağlantı", "noun", "The internet connection is unstable.", "İnternet bağlantısı istikrarsız."],
      ["online", "çevrimiçi", "adjective", "She is online right now.", "Şu an çevrimiçi."],
      ["offline", "çevrimdışı", "adjective", "The app also works offline.", "Uygulama çevrimdışı da çalışır."],
      ["digital", "dijital", "adjective", "We prefer digital tickets.", "Dijital biletleri tercih ediyoruz."],
      ["software", "yazılım", "noun", "This software is easy to use.", "Bu yazılım kullanımı kolay."],
      ["hardware", "donanım", "noun", "The store sells computer hardware.", "Mağaza bilgisayar donanımı satıyor."],
      ["code", "kod", "noun", "She is learning to write code.", "Kod yazmayı öğreniyor."],
      ["robot", "robot", "noun", "The factory uses robots for packing.", "Fabrika paketleme için robot kullanıyor."],
      ["settings", "ayarlar", "noun", "Change the language in the settings.", "Dili ayarlardan değiştir."],
      ["notification", "bildirim", "noun", "I turned off the notifications.", "Bildirimleri kapattım."],
      ["browser", "tarayıcı", "noun", "Which browser do you use?", "Hangi tarayıcıyı kullanıyorsun?"],
      ["file", "dosya", "noun", "I saved the file on my desktop.", "Dosyayı masaüstüme kaydettim."],
      ["folder", "klasör", "noun", "Put the photos in a new folder.", "Fotoğrafları yeni bir klasöre koy."],
      ["backup", "yedek", "noun", "Always keep a backup of your files.", "Dosyalarının her zaman bir yedeğini tut."],
    ],
  },
  {
    topic: "Alışveriş & Para",
    rows: [
      ["price", "fiyat", "noun", "The price of coffee went up.", "Kahvenin fiyatı arttı."],
      ["discount", "indirim", "noun", "We got a discount on the shoes.", "Ayakkabılarda indirim aldık."],
      ["sale", "indirim", "noun", "The store has a big sale this week.", "Mağazada bu hafta büyük indirim var."],
      ["receipt", "fiş", "noun", "Keep your receipt for the return.", "İade için fişini sakla."],
      ["cash", "nakit", "noun", "I only have cash with me.", "Yanımda sadece nakit var."],
      ["wallet", "cüzdan", "noun", "I left my wallet at home.", "Cüzdanımı evde unuttum."],
      ["budget", "bütçe", "noun", "We have a small budget for this trip.", "Bu seyahat için küçük bir bütçemiz var."],
      ["save", "biriktirmek", "verb", "She saves money every month.", "Her ay para biriktiriyor."],
      ["spend", "harcamak", "verb", "We spent too much on the weekend.", "Hafta sonu çok fazla harcadık."],
      ["borrow", "ödünç almak", "verb", "Can I borrow some money from you?", "Senden biraz para ödünç alabilir miyim?"],
      ["lend", "ödünç vermek", "verb", "He lent me his umbrella.", "Bana şemsiyesini ödünç verdi."],
      ["loan", "kredi", "noun", "They took a loan to buy a car.", "Araba almak için kredi çektiler."],
      ["debt", "borç", "noun", "She paid off all her debt.", "Tüm borcunu ödedi."],
      ["income", "gelir", "noun", "Her income increased this year.", "Bu yıl geliri arttı."],
      ["expense", "gider", "noun", "Rent is our biggest expense.", "Kira en büyük giderimiz."],
      ["invoice", "fatura", "noun", "The invoice arrived by email.", "Fatura e-posta ile geldi."],
      ["refund", "geri ödeme", "noun", "I asked for a refund.", "Geri ödeme talep ettim."],
      ["size", "beden", "noun", "Do you have this in a bigger size?", "Bunun daha büyük bir bedeni var mı?"],
      ["quality", "kalite", "noun", "The quality of this bag is excellent.", "Bu çantanın kalitesi mükemmel."],
      ["brand", "marka", "noun", "She always buys the same brand.", "Her zaman aynı markayı alır."],
      ["customer", "müşteri", "noun", "The customer asked for a discount.", "Müşteri indirim istedi."],
      ["cashier", "kasiyer", "noun", "The cashier was very friendly.", "Kasiyer çok arkadaş canlısıydı."],
      ["delivery", "teslimat", "noun", "Delivery takes three days.", "Teslimat üç gün sürüyor."],
      ["order", "sipariş", "noun", "I placed an order online.", "Çevrimiçi bir sipariş verdim."],
      ["package", "paket", "noun", "The package arrived this morning.", "Paket bu sabah geldi."],
      ["warranty", "garanti", "noun", "This laptop has a two-year warranty.", "Bu dizüstü bilgisayarın iki yıl garantisi var."],
      ["bargain", "pazarlık yapmak", "verb", "He bargained for a better price.", "Daha iyi bir fiyat için pazarlık yaptı."],
      ["afford", "gücü yetmek", "verb", "We can't afford a new car this year.", "Bu yıl yeni bir arabaya gücümüz yetmiyor."],
      ["valuable", "değerli", "adjective", "That ring is very valuable.", "O yüzük çok değerli."],
      ["coupon", "kupon", "noun", "I used a coupon at the checkout.", "Kasada bir kupon kullandım."],
      ["installment", "taksit", "noun", "You can pay in installments.", "Taksitle ödeyebilirsin."],
      ["exchange rate", "döviz kuru", "phrase", "The exchange rate changed overnight.", "Döviz kuru bir gecede değişti."],
      ["checkout", "kasa", "noun", "The line at checkout was long.", "Kasadaki sıra uzundu."],
      ["shopping mall", "alışveriş merkezi", "phrase", "We spent the afternoon at the shopping mall.", "Öğleden sonrayı alışveriş merkezinde geçirdik."],
      ["online shopping", "çevrimiçi alışveriş", "phrase", "Online shopping saves a lot of time.", "Çevrimiçi alışveriş çok zaman kazandırır."],
      ["credit card", "kredi kartı", "phrase", "I paid with my credit card.", "Kredi kartımla ödedim."],
    ],
  },
  {
    topic: "Duygular & Görüşler",
    rows: [
      ["opinion", "görüş", "noun", "What is your opinion about this plan?", "Bu plan hakkındaki görüşün nedir?"],
      ["agree", "aynı fikirde olmak", "verb", "I agree with you completely.", "Seninle tamamen aynı fikirdeyim."],
      ["disagree", "aynı fikirde olmamak", "verb", "We disagree about the schedule.", "Program konusunda aynı fikirde değiliz."],
      ["argument", "tartışma", "noun", "They had a small argument.", "Küçük bir tartışma yaşadılar."],
      ["complain", "şikayet etmek", "verb", "She complained about the noise.", "Gürültü hakkında şikayet etti."],
      ["apologize", "özür dilemek", "verb", "He apologized for being late.", "Geç kaldığı için özür diledi."],
      ["forgive", "affetmek", "verb", "I forgave him quickly.", "Onu hızlıca affettim."],
      ["disappointed", "hayal kırıklığına uğramış", "adjective", "She was disappointed with the results.", "Sonuçlardan dolayı hayal kırıklığına uğradı."],
      ["excited", "heyecanlı", "adjective", "We are excited about the trip.", "Seyahat için heyecanlıyız."],
      ["nervous", "gergin", "adjective", "He felt nervous before the exam.", "Sınavdan önce gergin hissetti."],
      ["confident", "kendinden emin", "adjective", "She spoke with confidence.", "Kendinden emin bir şekilde konuştu."],
      ["jealous", "kıskanç", "adjective", "He felt a bit jealous of his brother.", "Kardeşini biraz kıskandı."],
      ["proud", "gururlu", "adjective", "I am proud of my daughter.", "Kızımla gurur duyuyorum."],
      ["embarrassed", "utanmış", "adjective", "She was embarrassed by the mistake.", "Hatadan dolayı utandı."],
      ["surprised", "şaşırmış", "adjective", "We were surprised by the news.", "Habere şaşırdık."],
      ["confused", "kafası karışmış", "adjective", "I am confused about the directions.", "Yönler konusunda kafam karıştı."],
      ["bored", "sıkılmış", "adjective", "The kids got bored quickly.", "Çocuklar çabuk sıkıldı."],
      ["curious", "meraklı", "adjective", "She is curious about other cultures.", "Diğer kültürler hakkında meraklı."],
      ["grateful", "minnettar", "adjective", "I am grateful for your help.", "Yardımın için minnettarım."],
      ["generous", "cömert", "adjective", "He is very generous with his time.", "Zamanı konusunda çok cömert."],
      ["selfish", "bencil", "adjective", "It was a selfish decision.", "Bu bencil bir karardı."],
      ["honest", "dürüst", "adjective", "She gave an honest answer.", "Dürüst bir cevap verdi."],
      ["polite", "kibar", "adjective", "The staff were very polite.", "Personel çok kibardı."],
      ["rude", "kaba", "adjective", "It's rude to interrupt people.", "İnsanların sözünü kesmek kabalıktır."],
      ["patient", "sabırlı", "adjective", "The teacher was very patient.", "Öğretmen çok sabırlıydı."],
      ["stubborn", "inatçı", "adjective", "My grandfather is quite stubborn.", "Büyükbabam oldukça inatçıdır."],
      ["shy", "utangaç", "adjective", "The new student seems shy.", "Yeni öğrenci utangaç görünüyor."],
      ["cheerful", "neşeli", "adjective", "She has a cheerful personality.", "Neşeli bir kişiliği var."],
      ["worried", "endişeli", "adjective", "I am worried about the exam results.", "Sınav sonuçları için endişeliyim."],
      ["relieved", "rahatlamış", "adjective", "We felt relieved after the call.", "Aramadan sonra rahatladık."],
      ["ashamed", "utanmış", "adjective", "He felt ashamed of his behavior.", "Davranışından utandı."],
      ["hopeful", "umutlu", "adjective", "I am hopeful about the future.", "Gelecek konusunda umutluyum."],
      ["satisfied", "memnun", "adjective", "The customer was satisfied with the service.", "Müşteri hizmetten memnun kaldı."],
      ["comfortable", "rahat", "adjective", "This chair is very comfortable.", "Bu sandalye çok rahat."],
      ["frustrated", "hayal kırıklığına uğramış", "adjective", "He was frustrated with the delay.", "Gecikmeden dolayı hayal kırıklığına uğradı."],
      ["sympathetic", "anlayışlı", "adjective", "She was very sympathetic to my situation.", "Durumuma karşı çok anlayışlıydı."],
    ],
  },
  {
    topic: "Çevre & Hava Durumu",
    rows: [
      ["climate", "iklim", "noun", "The climate here is mild.", "Buradaki iklim ılımlı."],
      ["temperature", "sıcaklık", "noun", "The temperature dropped suddenly.", "Sıcaklık aniden düştü."],
      ["pollution", "kirlilik", "noun", "Air pollution is a big problem in the city.", "Hava kirliliği şehirde büyük bir sorun."],
      ["recycle", "geri dönüştürmek", "verb", "We recycle paper and plastic.", "Kağıt ve plastiği geri dönüştürüyoruz."],
      ["environment", "çevre", "noun", "We must protect the environment.", "Çevreyi korumalıyız."],
      ["energy", "enerji", "noun", "Solar energy is becoming cheaper.", "Güneş enerjisi giderek ucuzluyor."],
      ["solar", "güneşe ait", "adjective", "They installed solar panels on the roof.", "Çatıya güneş panelleri kurdular."],
      ["electricity", "elektrik", "noun", "The electricity went out last night.", "Dün gece elektrik kesildi."],
      ["drought", "kuraklık", "noun", "The region suffered a long drought.", "Bölge uzun bir kuraklık yaşadı."],
      ["flood", "sel", "noun", "The flood damaged many houses.", "Sel birçok evi hasara uğrattı."],
      ["storm", "fırtına", "noun", "A storm is coming this evening.", "Bu akşam bir fırtına geliyor."],
      ["thunder", "gök gürültüsü", "noun", "We heard thunder in the distance.", "Uzaktan gök gürültüsü duyduk."],
      ["lightning", "şimşek", "noun", "Lightning lit up the sky.", "Şimşek gökyüzünü aydınlattı."],
      ["humidity", "nem", "noun", "The humidity makes it feel hotter.", "Nem havayı daha sıcak hissettiriyor."],
      ["forecast", "hava tahmini", "noun", "The forecast says it will rain tomorrow.", "Hava tahmini yarın yağmur yağacağını söylüyor."],
      ["season", "mevsim", "noun", "Autumn is my favorite season.", "Sonbahar en sevdiğim mevsim."],
      ["spring", "ilkbahar", "noun", "Flowers bloom in spring.", "İlkbaharda çiçekler açar."],
      ["summer", "yaz", "noun", "We travel a lot in summer.", "Yazın çok seyahat ederiz."],
      ["autumn", "sonbahar", "noun", "The leaves turn orange in autumn.", "Yapraklar sonbaharda turuncuya döner."],
      ["winter", "kış", "noun", "It snows a lot in winter here.", "Burada kışın çok kar yağar."],
      ["disaster", "afet", "noun", "The earthquake was a natural disaster.", "Deprem doğal bir afetti."],
      ["natural", "doğal", "adjective", "This park has natural beauty.", "Bu parkın doğal bir güzelliği var."],
      ["protect", "korumak", "verb", "We should protect the forests.", "Ormanları korumalıyız."],
      ["waste", "atık", "noun", "The city reduced its waste this year.", "Şehir bu yıl atığını azalttı."],
      ["plastic", "plastik", "noun", "Try to use less plastic.", "Daha az plastik kullanmaya çalış."],
      ["renewable", "yenilenebilir", "adjective", "Renewable energy is growing fast.", "Yenilenebilir enerji hızla büyüyor."],
      ["resource", "kaynak", "noun", "Water is a limited resource.", "Su sınırlı bir kaynaktır."],
      ["wildlife", "yaban hayatı", "noun", "The reserve protects local wildlife.", "Koruma alanı yerel yaban hayatını koruyor."],
      ["endangered", "nesli tükenmekte olan", "adjective", "This is an endangered species.", "Bu nesli tükenmekte olan bir türdür."],
      ["conservation", "koruma", "noun", "The group works on ocean conservation.", "Grup okyanus koruması üzerinde çalışıyor."],
      ["emission", "emisyon", "noun", "Cars produce carbon emissions.", "Arabalar karbon emisyonu üretir."],
      ["sustainable", "sürdürülebilir", "adjective", "We need more sustainable habits.", "Daha sürdürülebilir alışkanlıklara ihtiyacımız var."],
      ["ecosystem", "ekosistem", "noun", "The lake has a fragile ecosystem.", "Gölün hassas bir ekosistemi var."],
      ["global warming", "küresel ısınma", "phrase", "Global warming affects the whole planet.", "Küresel ısınma tüm gezegeni etkiliyor."],
    ],
  },
  {
    topic: "Sosyal Yaşam",
    rows: [
      ["invite", "davet etmek", "verb", "She invited us to her birthday party.", "Bizi doğum günü partisine davet etti."],
      ["celebrate", "kutlamak", "verb", "We celebrated his graduation together.", "Mezuniyetini birlikte kutladık."],
      ["birthday", "doğum günü", "noun", "Today is my sister's birthday.", "Bugün kız kardeşimin doğum günü."],
      ["anniversary", "yıl dönümü", "noun", "They celebrated their wedding anniversary.", "Evlilik yıl dönümlerini kutladılar."],
      ["wedding", "düğün", "noun", "The wedding was beautiful.", "Düğün çok güzeldi."],
      ["festival", "festival", "noun", "The music festival lasted three days.", "Müzik festivali üç gün sürdü."],
      ["holiday", "tatil", "noun", "We are planning a holiday in July.", "Temmuzda bir tatil planlıyoruz."],
      ["custom", "âdet", "noun", "It is a local custom to remove your shoes.", "Ayakkabılarını çıkarmak yerel bir âdettir."],
      ["community", "topluluk", "noun", "This community is very welcoming.", "Bu topluluk çok misafirperver."],
      ["relationship", "ilişki", "noun", "They have a strong relationship.", "Güçlü bir ilişkileri var."],
      ["friendship", "arkadaşlık", "noun", "Their friendship lasted for years.", "Arkadaşlıkları yıllarca sürdü."],
      ["trust", "güven", "noun", "Trust is important in any relationship.", "Güven her ilişkide önemlidir."],
      ["support", "destek", "noun", "She gave me a lot of support.", "Bana çok destek verdi."],
      ["volunteer", "gönüllü", "noun", "He works as a volunteer at the shelter.", "Barınakta gönüllü olarak çalışıyor."],
      ["charity", "hayır kurumu", "noun", "They donated money to a charity.", "Bir hayır kurumuna para bağışladılar."],
      ["roommate", "ev arkadaşı", "noun", "My roommate is very tidy.", "Ev arkadaşım çok düzenlidir."],
      ["acquaintance", "tanıdık", "noun", "He is just an acquaintance, not a close friend.", "O sadece bir tanıdık, yakın arkadaş değil."],
      ["stranger", "yabancı", "noun", "Don't talk to strangers.", "Yabancılarla konuşma."],
      ["introduce", "tanıştırmak", "verb", "Let me introduce you to my friend.", "Seni arkadaşımla tanıştırayım."],
      ["greet", "selamlamak", "verb", "He greeted everyone warmly.", "Herkesi sıcak bir şekilde selamladı."],
      ["gathering", "toplanma", "noun", "We had a small family gathering.", "Küçük bir aile toplanması yaptık."],
      ["party", "parti", "noun", "The party starts at eight.", "Parti saat sekizde başlıyor."],
      ["celebration", "kutlama", "noun", "The celebration lasted all night.", "Kutlama bütün gece sürdü."],
      ["congratulate", "tebrik etmek", "verb", "I congratulated her on the new job.", "Onu yeni işi için tebrik ettim."],
      ["gossip", "dedikodu", "noun", "I don't like listening to gossip.", "Dedikodu dinlemeyi sevmem."],
      ["rumor", "söylenti", "noun", "There is a rumor about the new manager.", "Yeni müdür hakkında bir söylenti var."],
      ["reconcile", "barışmak", "verb", "The two friends finally reconciled.", "İki arkadaş sonunda barıştı."],
      ["compromise", "uzlaşmak", "verb", "They compromised on the plan.", "Plan konusunda uzlaştılar."],
      ["cooperate", "iş birliği yapmak", "verb", "The teams cooperated well together.", "Takımlar birbirleriyle iyi iş birliği yaptı."],
      ["neighbor", "komşu", "noun", "Our neighbor brought us a cake.", "Komşumuz bize kek getirdi."],
      ["condolence", "başsağlığı", "noun", "We offered our condolences to the family.", "Aileye başsağlığı dileklerimizi sunduk."],
      ["hospitality", "misafirperverlik", "noun", "We were impressed by their hospitality.", "Misafirperverliklerinden etkilendik."],
      ["etiquette", "görgü kuralları", "noun", "Table etiquette differs between cultures.", "Sofra görgü kuralları kültürler arasında farklılık gösterir."],
      ["reunion", "buluşma", "noun", "We had a family reunion this summer.", "Bu yaz bir aile buluşması yaptık."],
      ["neighborhood", "mahalle", "noun", "This neighborhood is very quiet.", "Bu mahalle çok sessiz."],
    ],
  },
];

function pickDistractors(pool: Row[], index: number): string[] {
  const others = [...pool.slice(index + 1), ...pool.slice(0, index)];
  const meanings = Array.from(new Set(others.map((row) => row[1]))).filter((m) => m !== pool[index][1]);
  return meanings.slice(0, 2);
}

export const a2GeneratedQuestions: MeaningMatchQuestion[] = TOPICS.flatMap((block) =>
  block.rows.map((row, index) => {
    const [word, meaningTr, partOfSpeech, exampleSentence, exampleTranslation] = row;
    const wrongOptions = pickDistractors(block.rows, index);
    return {
      id: `a2-core-${word.replace(/[^a-z]/gi, "-").toLowerCase()}`,
      mode: "MEANING_MATCH" as const,
      level: "A2" as const,
      topic: block.topic,
      word,
      meaning: meaningTr,
      wrongOptions,
      xp: computeXpReward("A2", word),
      difficulty: computeDifficulty("A2", word),
      partOfSpeech,
      exampleSentence,
      exampleTranslation,
      contextNote: `${block.topic} konusu için A2 seviyesi çekirdek kelime.`,
      pronunciation: word,
      hint: `${block.topic} konusundaki kelimeyi seç.`,
      prompt: word,
      answer: meaningTr,
      options: [meaningTr, ...wrongOptions],
    };
  })
);
