import { MeaningMatchQuestion } from "../../types/content";

export const b1MeaningMatchQuestions: MeaningMatchQuestion[] = [
  {
    id: "b1-mm-01",
    mode: "MEANING_MATCH",
    level: "B1",
    topic: "Gelişim & Başarı",
    word: "flourish",
    meaning: "gelişmek",
    wrongOptions: ["gerilemek", "durmak"],
    xp: 20,
    difficulty: 3,
    phonetic: "/ˈflʌr.ɪʃ/",
    partOfSpeech: "verb",
    exampleSentence: "With daily watering, your vocabulary garden will flourish.",
    exampleTranslation: "Günlük sulama ile kelime bahçen gelişecektir.",
    contextNote: "Sağlıklı, başarılı ve güçlü bir şekilde serpilmeyi anlatır.",
    pronunciation: "flourish",
    hint: "Sağlıklı, güçlü ve verimli bir şekilde büyüyüp serpilmek.",
    prompt: "flourish",
    answer: "gelişmek",
    options: ["gelişmek", "gerilemek", "durmak"],
  },
  {
    id: "b1-mm-02",
    mode: "MEANING_MATCH",
    level: "B1",
    topic: "Karakter & Güç",
    word: "resilient",
    meaning: "dayanıklı",
    wrongOptions: ["kırılgan", "zayıf"],
    xp: 20,
    difficulty: 3,
    phonetic: "/rɪˈzɪl.jənt/",
    partOfSpeech: "adjective",
    exampleSentence: "Resilient learners overcome challenges with persistence.",
    exampleTranslation: "Dayanıklı öğreniciler zorlukları azimle aşarlar.",
    contextNote: "Zorluklar karşısında esneyip geri toparlanabilme gücü.",
    pronunciation: "resilient",
    hint: "Zorluklar karşısında yılmayan, çabuk toparlanan.",
    prompt: "resilient",
    answer: "dayanıklı",
    options: ["dayanıklı", "kırılgan", "zayıf"],
  },
  {
    id: "b1-mm-03",
    mode: "MEANING_MATCH",
    level: "B1",
    topic: "Tarım & Üretim",
    word: "cultivate",
    meaning: "yetiştirmek",
    wrongOptions: ["tüketmek", "bırakmak"],
    xp: 20,
    difficulty: 3,
    phonetic: "/ˈkʌl.tɪ.veɪt/",
    partOfSpeech: "verb",
    exampleSentence: "It takes patience to cultivate good learning habits.",
    exampleTranslation: "İyi öğrenme alışkanlıkları yetiştirmek sabır gerektirir.",
    contextNote: "Toprağı işlemek veya yetenek/beceri geliştirmek.",
    pronunciation: "cultivate",
    hint: "Toprağı işleyerek bitki veya fikir yetiştirip geliştirmek.",
    prompt: "cultivate",
    answer: "yetiştirmek",
    options: ["yetiştirmek", "tüketmek", "bırakmak"],
  },
  {
    id: "b1-mm-04",
    mode: "MEANING_MATCH",
    level: "B1",
    topic: "Doğa & Bereket",
    word: "harvest",
    meaning: "hasat",
    wrongOptions: ["ekim", "sulama"],
    xp: 20,
    difficulty: 3,
    phonetic: "/ˈhɑː.vɪst/",
    partOfSpeech: "noun",
    exampleSentence: "Farmers celebrate a bountiful autumn harvest.",
    exampleTranslation: "Çiftçiler bereketli bir sonbahar hasadını kutlar.",
    contextNote: "Emeğin karşılığı olan ürün toplama zamanı ve mahsul.",
    pronunciation: "harvest",
    hint: "Olgunlaşan ekinlerin toplanması mevsimi veya ürünü.",
    prompt: "harvest",
    answer: "hasat",
    options: ["hasat", "ekim", "sulama"],
  },
  {
    id: "b1-mm-05",
    mode: "MEANING_MATCH",
    level: "B1",
    topic: "Çevre & Koruma",
    word: "preserve",
    meaning: "korumak",
    wrongOptions: ["harcamak", "yıpratmak"],
    xp: 20,
    difficulty: 3,
    phonetic: "/prɪˈzɜːv/",
    partOfSpeech: "verb",
    exampleSentence: "We must preserve natural habitats for future generations.",
    exampleTranslation: "Doğal yaşam alanlarını gelecek nesiller için korumalıyız.",
    contextNote: "Özgünlüğünü kaybetmeden muhafaza etmek.",
    pronunciation: "preserve",
    hint: "Doğayı veya değerleri bozulmadan muhafaza etmek.",
    prompt: "preserve",
    answer: "korumak",
    options: ["korumak", "harcamak", "yıpratmak"],
  },
];

export const b1Questions = b1MeaningMatchQuestions;
