import { MeaningMatchQuestion } from "../../types/content";

export const b2MeaningMatchQuestions: MeaningMatchQuestion[] = [
  {
    id: "b2-mm-01",
    mode: "MEANING_MATCH",
    level: "B2",
    topic: "Ekoloji & Çevre",
    word: "sustainable",
    meaning: "sürdürülebilir",
    wrongOptions: ["geçici", "tükenen"],
    xp: 25,
    difficulty: 4,
    phonetic: "/səˈsteɪ.nə.bəl/",
    partOfSpeech: "adjective",
    exampleSentence: "Sustainable practices ensure balance between humans and nature.",
    exampleTranslation: "Sürdürülebilir uygulamalar insan ve doğa arasında denge sağlar.",
    contextNote: "Gelecek kaynaklarını tüketmeden devam edebilen yöntem.",
    pronunciation: "sustainable",
    hint: "Doğal dengeyi bozmadan geleceğe taşınabilen yöntem.",
    prompt: "sustainable",
    answer: "sürdürülebilir",
    options: ["sürdürülebilir", "geçici", "tükenen"],
  },
  {
    id: "b2-mm-02",
    mode: "MEANING_MATCH",
    level: "B2",
    topic: "Biyoloji & Çevre",
    word: "biodiversity",
    meaning: "biyoçeşitlilik",
    wrongOptions: ["tekdüzelik", "kirlilik"],
    xp: 25,
    difficulty: 4,
    phonetic: "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/",
    partOfSpeech: "noun",
    exampleSentence: "Rainforests boast the highest biodiversity on the planet.",
    exampleTranslation: "Yağmur ormanları gezegendeki en yüksek biyoçeşitliliğe sahiptir.",
    contextNote: "Bir ekosistemde yaşayan canlı türlerinin zenginliği.",
    pronunciation: "biodiversity",
    hint: "Belirli bir ekosistemdeki canlı türlerinin zengin çeşitliliği.",
    prompt: "biodiversity",
    answer: "biyoçeşitlilik",
    options: ["biyoçeşitlilik", "tekdüzelik", "kirlilik"],
  },
  {
    id: "b2-mm-03",
    mode: "MEANING_MATCH",
    level: "B2",
    topic: "Huzur & Zihin",
    word: "tranquility",
    meaning: "huzur",
    wrongOptions: ["kargaşa", "telaş"],
    xp: 25,
    difficulty: 4,
    phonetic: "/træŋˈkwɪl.ə.ti/",
    partOfSpeech: "noun",
    exampleSentence: "She walked through the botanical garden seeking tranquility.",
    exampleTranslation: "Huzur arayarak botanik bahçesinde yürüdü.",
    contextNote: "Zihinsel ve çevresel derin dinginlik hali.",
    pronunciation: "tranquility",
    hint: "Sakin, gürültüsüz ve dingin olma hali.",
    prompt: "tranquility",
    answer: "huzur",
    options: ["huzur", "kargaşa", "telaş"],
  },
  {
    id: "b2-mm-04",
    mode: "MEANING_MATCH",
    level: "B2",
    topic: "Beslenme & Doğa",
    word: "nourishment",
    meaning: "besin",
    wrongOptions: ["zehir", "yoksunluk"],
    xp: 25,
    difficulty: 4,
    phonetic: "/ˈnʌr.ɪʃ.mənt/",
    partOfSpeech: "noun",
    exampleSentence: "Sunlight provides vital nourishment for flowering plants.",
    exampleTranslation: "Güneş ışığı çiçek açan bitkiler için hayati besin sağlar.",
    contextNote: "Gelişim ve büyüme için gerekli temel gıda.",
    pronunciation: "nourishment",
    hint: "Canlıların büyümesi ve sağlıklı kalması için gereken gıda/beslenme.",
    prompt: "nourishment",
    answer: "besin",
    options: ["besin", "zehir", "yoksunluk"],
  },
];

export const b2Questions = b2MeaningMatchQuestions;
