import { MeaningMatchQuestion } from "../../types/content";

export const c1MeaningMatchQuestions: MeaningMatchQuestion[] = [
  {
    id: "c1-mm-01",
    mode: "MEANING_MATCH",
    level: "C1",
    topic: "Felsefe & Zaman",
    word: "ephemeral",
    meaning: "kısa ömürlü",
    wrongOptions: ["sonsuz", "kalıcı"],
    xp: 30,
    difficulty: 5,
    phonetic: "/ɪˈfem.ər.əl/",
    partOfSpeech: "adjective",
    exampleSentence: "Morning dew on fresh petals is exquisite yet ephemeral.",
    exampleTranslation: "Taze taç yapraklarındaki sabah çiyi enfes ama kısa ömürlüdür.",
    contextNote: "Sadece çok kısa bir an süren geçici güzellikler için kullanılır.",
    pronunciation: "ephemeral",
    hint: "Çok kısa süren, geçici ve anlık güzellik.",
    prompt: "ephemeral",
    answer: "kısa ömürlü",
    options: ["kısa ömürlü", "sonsuz", "kalıcı"],
  },
  {
    id: "c1-mm-02",
    mode: "MEANING_MATCH",
    level: "C1",
    topic: "Biyoloji & Etkileşim",
    word: "symbiotic",
    meaning: "ortakyaşar",
    wrongOptions: ["ayrık", "parazit"],
    xp: 30,
    difficulty: 5,
    phonetic: "/ˌsɪm.baɪˈɒt.ɪk/",
    partOfSpeech: "adjective",
    exampleSentence: "Bees and flowers share a symbiotic relationship in the garden.",
    exampleTranslation: "Arılar ve çiçekler bahçede ortakyaşar bir ilişki paylaşır.",
    contextNote: "Her iki tarafın da birbirine yarar sağladığı karşılıklı yaşam.",
    pronunciation: "symbiotic",
    hint: "İki farklı canlının karşılıklı fayda sağlayarak birlikte yaşaması.",
    prompt: "symbiotic",
    answer: "ortakyaşar",
    options: ["ortakyaşar", "ayrık", "parazit"],
  },
  {
    id: "c1-mm-03",
    mode: "MEANING_MATCH",
    level: "C1",
    topic: "Işık & Fizik",
    word: "luminescence",
    meaning: "ışıma",
    wrongOptions: ["karanlık", "gölge"],
    xp: 30,
    difficulty: 5,
    phonetic: "/ˌluː.mɪˈnes.əns/",
    partOfSpeech: "noun",
    exampleSentence: "Fireflies illuminated the midnight garden with soft luminescence.",
    exampleTranslation: "Ateşböcekleri gece yarısı bahçesini yumuşak bir ışımayla aydınlattı.",
    contextNote: "Isı üretmeksizin ışık yayma olgusu.",
    pronunciation: "luminescence",
    hint: "Isı yaymadan ışık çıkarma veya parıldama olayı.",
    prompt: "luminescence",
    answer: "ışıma",
    options: ["ışıma", "karanlık", "gölge"],
  },
  {
    id: "c1-mm-04",
    mode: "MEANING_MATCH",
    level: "C1",
    topic: "Botanik",
    word: "perennial",
    meaning: "çok yıllık",
    wrongOptions: ["mevsimlik", "kurak"],
    xp: 30,
    difficulty: 5,
    phonetic: "/pəˈren.i.əl/",
    partOfSpeech: "adjective",
    exampleSentence: "Lavender is a resilient perennial shrub beloved by gardeners.",
    exampleTranslation: "Lavanta, bahçıvanlar tarafından sevilen dayanıklı çok yıllık bir çalıdır.",
    contextNote: "Her yıl yeniden ekilmeye gerek kalmadan yaşayan bitkiler.",
    pronunciation: "perennial",
    hint: "Yıllar boyunca yaşamını ve büyümesini sürdüren bitki.",
    prompt: "perennial",
    answer: "çok yıllık",
    options: ["çok yıllık", "mevsimlik", "kurak"],
  },
];

export const c1Questions = c1MeaningMatchQuestions;
