import { MeaningMatchQuestion } from "../../types/content";

export const c2MeaningMatchQuestions: MeaningMatchQuestion[] = [
  {
    id: "c2-mm-01",
    mode: "MEANING_MATCH",
    level: "C2",
    topic: "Edebi Botanik",
    word: "verdant",
    meaning: "yemyeşil",
    wrongOptions: ["çorak", "solgun"],
    xp: 35,
    difficulty: 5,
    phonetic: "/ˈvɜː.dənt/",
    partOfSpeech: "adjective",
    exampleSentence: "The valley stretched before them, a verdant carpet of ancient flora.",
    exampleTranslation: "Vadi önlerinde kadim bitki örtüsünden yemyeşil bir halı gibi uzanıyordu.",
    contextNote: "Zengin, taze ve gür yeşillikle kaplı manzaralar için edebi sıfat.",
    pronunciation: "verdant",
    hint: "Gür ve canlı yeşil bitki örtüsüyle kaplı verimli alan.",
    prompt: "verdant",
    answer: "yemyeşil",
    options: ["yemyeşil", "çorak", "solgun"],
  },
  {
    id: "c2-mm-02",
    mode: "MEANING_MATCH",
    level: "C2",
    topic: "Edebi Sıfatlar",
    word: "serendipity",
    meaning: "mutlu tesadüf",
    wrongOptions: ["kasıt", "talihsizlik"],
    xp: 35,
    difficulty: 5,
    phonetic: "/ˌser.ənˈdɪp.ə.ti/",
    partOfSpeech: "noun",
    exampleSentence: "Finding an old rare botanical manuscript was pure serendipity.",
    exampleTranslation: "Eski nadir bir botanik el yazması bulmak tam anlamıyla mutlu bir tesadüftü.",
    contextNote: "Aramazken beklenmedik şekilde şanslı bir keşif yapma hali.",
    pronunciation: "serendipity",
    hint: "Aramazken tesadüfen değerli ve güzel bir şey keşfetme şansı.",
    prompt: "serendipity",
    answer: "mutlu tesadüf",
    options: ["mutlu tesadüf", "kasıt", "talihsizlik"],
  },
  {
    id: "c2-mm-03",
    mode: "MEANING_MATCH",
    level: "C2",
    topic: "Botanik & Ormancılık",
    word: "deciduous",
    meaning: "yaprak döken",
    wrongOptions: ["herdaim yeşil", "iğne yapraklı"],
    xp: 35,
    difficulty: 5,
    phonetic: "/dɪˈsɪdʒ.u.əs/",
    partOfSpeech: "adjective",
    exampleSentence: "Deciduous forests transform into brilliant tapestries in autumn.",
    exampleTranslation: "Yaprak döken ormanlar sonbaharda parlak dokumalara dönüşür.",
    contextNote: "Mevsimsel olarak yapraklarını yenileyen ağaç türleri.",
    pronunciation: "deciduous",
    hint: "Sonbaharda yapraklarını döküp baharda yenilerini çıkaran ağaç türü.",
    prompt: "deciduous",
    answer: "yaprak döken",
    options: ["yaprak döken", "herdaim yeşil", "iğne yapraklı"],
  },
];

export const c2Questions = c2MeaningMatchQuestions;
