/**
 * Real, per-word example sentences for A1_CORE_VOCABULARY. Replaces the
 * generic "Learn and use the word 'x' in a simple sentence." template that
 * every generated A1 question used to carry — that template taught nothing
 * about how a word actually behaves in context.
 *
 * Keyed by the lowercase English word. Sentences are kept short (A1-level:
 * 4-9 words) and use the word in a natural, everyday way.
 */
export interface ExampleSentence {
  en: string;
  tr: string;
}

export const A1_EXAMPLE_SENTENCES: Record<string, ExampleSentence> = {
  // people
  "i": { en: "I live in a small town.", tr: "Küçük bir kasabada yaşıyorum." },
  "you": { en: "You speak English very well.", tr: "İngilizceyi çok iyi konuşuyorsun." },
  "he": { en: "He works at the hospital.", tr: "O hastanede çalışıyor." },
  "she": { en: "She is my best friend.", tr: "O benim en iyi arkadaşım." },
  "we": { en: "We meet every Friday.", tr: "Her cuma buluşuyoruz." },
  "they": { en: "They live next to the park.", tr: "Onlar parkın yanında yaşıyor." },
  "person": { en: "She is a very kind person.", tr: "O çok nazik bir kişi." },
  "people": { en: "Many people visit this city.", tr: "Bu şehri birçok insan ziyaret ediyor." },
  "man": { en: "The man is reading a newspaper.", tr: "Adam bir gazete okuyor." },
  "woman": { en: "The woman works at the bank.", tr: "Kadın bankada çalışıyor." },
  "child": { en: "The child is playing in the garden.", tr: "Çocuk bahçede oynuyor." },
  "baby": { en: "The baby is sleeping now.", tr: "Bebek şimdi uyuyor." },
  "friend": { en: "My friend called me yesterday.", tr: "Arkadaşım dün beni aradı." },
  "family": { en: "My family lives near the sea.", tr: "Ailem denizin yakınında yaşıyor." },
  "mother": { en: "My mother cooks dinner every night.", tr: "Annem her gece akşam yemeği pişirir." },
  "father": { en: "My father drives a taxi.", tr: "Babam taksi sürüyor." },
  "parent": { en: "Every parent wants their child to be happy.", tr: "Her ebeveyn çocuğunun mutlu olmasını ister." },
  "brother": { en: "My brother studies at university.", tr: "Erkek kardeşim üniversitede okuyor." },
  "sister": { en: "My sister lives in another city.", tr: "Kız kardeşim başka bir şehirde yaşıyor." },
  "son": { en: "Their son plays football on weekends.", tr: "Oğulları hafta sonları futbol oynuyor." },
  "daughter": { en: "Their daughter is learning to read.", tr: "Kızları okumayı öğreniyor." },
  "husband": { en: "Her husband works in an office.", tr: "Onun eşi bir ofiste çalışıyor." },
  "wife": { en: "His wife teaches at the school.", tr: "Onun eşi okulda öğretmenlik yapıyor." },
  "name": { en: "What is your name?", tr: "Senin adın ne?" },
  "teacher": { en: "The teacher explains the lesson clearly.", tr: "Öğretmen dersi açıkça anlatıyor." },
  "student": { en: "Every student needs a notebook.", tr: "Her öğrencinin bir deftere ihtiyacı var." },
  "doctor": { en: "The doctor checked my heart.", tr: "Doktor kalbimi kontrol etti." },
  "worker": { en: "The worker fixed the door.", tr: "Çalışan kapıyı tamir etti." },
  "neighbor": { en: "My neighbor has a friendly dog.", tr: "Komşumun sevimli bir köpeği var." },
  "boy": { en: "The boy is riding his bike.", tr: "Erkek çocuk bisikletine biniyor." },
  "girl": { en: "The girl is drawing a picture.", tr: "Kız çocuk resim çiziyor." },
  "adult": { en: "This film is only for adults.", tr: "Bu film sadece yetişkinler için." },
  "guest": { en: "We have a guest tonight.", tr: "Bu akşam bir misafirimiz var." },
  "visitor": { en: "The museum welcomes many visitors.", tr: "Müze birçok ziyaretçiyi ağırlıyor." },
  "team": { en: "Our team won the game.", tr: "Takımımız oyunu kazandı." },
  "group": { en: "We work in a small group.", tr: "Küçük bir grupta çalışıyoruz." },
  "class": { en: "Our class starts at nine.", tr: "Sınıfımız saat dokuzda başlıyor." },
  "member": { en: "She is a member of the club.", tr: "O kulübün bir üyesi." },
  "kind": { en: "The waiter was very kind to us.", tr: "Garson bize karşı çok naziktendi." },
  "welcome": { en: "Welcome to our home!", tr: "Evimize hoş geldiniz!" },

  // daily_life
  "day": { en: "Today is a beautiful day.", tr: "Bugün güzel bir gün." },
  "week": { en: "I go swimming twice a week.", tr: "Haftada iki kez yüzmeye gidiyorum." },
  "month": { en: "We are moving next month.", tr: "Gelecek ay taşınıyoruz." },
  "year": { en: "This year I learned English.", tr: "Bu yıl İngilizce öğrendim." },
  "morning": { en: "I drink coffee every morning.", tr: "Her sabah kahve içerim." },
  "afternoon": { en: "We usually meet in the afternoon.", tr: "Genellikle öğleden sonra buluşuruz." },
  "evening": { en: "I like walking in the evening.", tr: "Akşamları yürüyüş yapmayı severim." },
  "night": { en: "The city is quiet at night.", tr: "Şehir gece sessizdir." },
  "today": { en: "I have a lot of work today.", tr: "Bugün çok işim var." },
  "tomorrow": { en: "We will visit them tomorrow.", tr: "Yarın onları ziyaret edeceğiz." },
  "yesterday": { en: "It rained a lot yesterday.", tr: "Dün çok yağmur yağdı." },
  "now": { en: "I need to leave now.", tr: "Şimdi gitmem gerekiyor." },
  "later": { en: "I will call you later.", tr: "Seni sonra ararım." },
  "early": { en: "The bus arrived early today.", tr: "Otobüs bugün erken geldi." },
  "late": { en: "Sorry, I am running late.", tr: "Özür dilerim, geç kalıyorum." },
  "time": { en: "Do you have time to talk?", tr: "Konuşmaya vaktin var mı?" },
  "hour": { en: "The meeting lasted one hour.", tr: "Toplantı bir saat sürdü." },
  "minute": { en: "Wait a minute, please.", tr: "Lütfen bir dakika bekle." },
  "breakfast": { en: "I eat eggs for breakfast.", tr: "Kahvaltıda yumurta yerim." },
  "lunch": { en: "We had lunch at noon.", tr: "Öğlen öğle yemeği yedik." },
  "dinner": { en: "Dinner is ready at seven.", tr: "Akşam yemeği saat yedide hazır." },
  "work": { en: "I go to work by bus.", tr: "İşe otobüsle gidiyorum." },
  "school": { en: "My children walk to school.", tr: "Çocuklarım okula yürüyerek gider." },
  "lesson": { en: "Our next lesson is on Monday.", tr: "Bir sonraki dersimiz pazartesi." },
  "homework": { en: "I finished my homework early.", tr: "Ödevimi erken bitirdim." },
  "book": { en: "She is reading a good book.", tr: "O iyi bir kitap okuyor." },
  "page": { en: "Open your book to page ten.", tr: "Kitabınızı onuncu sayfaya açın." },
  "pen": { en: "Can I borrow your pen?", tr: "Kalemini ödünç alabilir miyim?" },
  "paper": { en: "I need a piece of paper.", tr: "Bir parça kağıda ihtiyacım var." },
  "bag": { en: "She carries her books in a bag.", tr: "Kitaplarını bir çantada taşıyor." },
  "phone": { en: "My phone battery is low.", tr: "Telefonumun pili az." },
  "computer": { en: "I work on my computer every day.", tr: "Her gün bilgisayarımda çalışırım." },
  "music": { en: "She listens to music while cooking.", tr: "Yemek yaparken müzik dinler." },
  "movie": { en: "We watched a great movie last night.", tr: "Dün gece harika bir film izledik." },
  "game": { en: "The children are playing a game.", tr: "Çocuklar bir oyun oynuyor." },
  "picture": { en: "He took a picture of the sunset.", tr: "Gün batımının resmini çekti." },
  "question": { en: "Can I ask you a question?", tr: "Sana bir soru sorabilir miyim?" },
  "answer": { en: "I don't know the answer.", tr: "Cevabı bilmiyorum." },
  "story": { en: "She told us an interesting story.", tr: "Bize ilginç bir hikâye anlattı." },
  "idea": { en: "That is a great idea.", tr: "Bu harika bir fikir." },

  // home_city
  "home": { en: "I usually stay home on Sundays.", tr: "Genellikle pazar günleri evde kalırım." },
  "house": { en: "Their house has a big garden.", tr: "Evlerinin büyük bir bahçesi var." },
  "room": { en: "My room is on the second floor.", tr: "Odam ikinci katta." },
  "door": { en: "Please close the door.", tr: "Lütfen kapıyı kapat." },
  "window": { en: "Open the window for fresh air.", tr: "Temiz hava için pencereyi aç." },
  "wall": { en: "There is a clock on the wall.", tr: "Duvarda bir saat var." },
  "floor": { en: "The kitchen is on the ground floor.", tr: "Mutfak zemin katta." },
  "table": { en: "We ate dinner at the table.", tr: "Akşam yemeğini masada yedik." },
  "chair": { en: "This chair is very comfortable.", tr: "Bu sandalye çok rahat." },
  "bed": { en: "I go to bed at eleven.", tr: "Saat on birde yatağa giderim." },
  "kitchen": { en: "My mother is cooking in the kitchen.", tr: "Annem mutfakta yemek pişiriyor." },
  "bathroom": { en: "The bathroom is next to my room.", tr: "Banyo odamın yanında." },
  "garden": { en: "We planted flowers in the garden.", tr: "Bahçeye çiçek diktik." },
  "street": { en: "Our house is on a quiet street.", tr: "Evimiz sessiz bir sokakta." },
  "road": { en: "This road leads to the city center.", tr: "Bu yol şehir merkezine çıkıyor." },
  "city": { en: "This city is very crowded.", tr: "Bu şehir çok kalabalık." },
  "town": { en: "I grew up in a small town.", tr: "Küçük bir kasabada büyüdüm." },
  "village": { en: "My grandparents live in a village.", tr: "Büyükannem ve büyükbabam bir köyde yaşıyor." },
  "shop": { en: "The shop closes at eight.", tr: "Dükkân saat sekizde kapanır." },
  "market": { en: "We buy vegetables at the market.", tr: "Sebzelerimizi pazardan alırız." },
  "bank": { en: "I need to go to the bank.", tr: "Bankaya gitmem gerekiyor." },
  "park": { en: "The children play in the park.", tr: "Çocuklar parkta oynuyor." },
  "station": { en: "The train station is very busy.", tr: "Tren istasyonu çok kalabalık." },
  "bus": { en: "I take the bus to work.", tr: "İşe otobüsle giderim." },
  "train": { en: "The train arrives at six.", tr: "Tren saat altıda geliyor." },
  "car": { en: "He parked his car outside.", tr: "Arabasını dışarıya park etti." },
  "bike": { en: "She rides her bike every morning.", tr: "Her sabah bisikletine biner." },
  "taxi": { en: "We took a taxi to the airport.", tr: "Havaalanına taksiyle gittik." },
  "ticket": { en: "I bought a ticket for the concert.", tr: "Konser için bir bilet aldım." },
  "map": { en: "Can you show me on the map?", tr: "Bana haritada gösterebilir misin?" },
  "left": { en: "Turn left at the corner.", tr: "Köşede sola dön." },
  "right": { en: "The bank is on the right.", tr: "Banka sağ tarafta." },
  "near": { en: "The shop is near my house.", tr: "Dükkân evime yakın." },
  "far": { en: "The airport is far from here.", tr: "Havaalanı buradan uzak." },
  "open": { en: "The store is open until nine.", tr: "Mağaza dokuza kadar açık." },
  "closed": { en: "The library is closed today.", tr: "Kütüphane bugün kapalı." },
  "address": { en: "Please write down your address.", tr: "Lütfen adresini yaz." },
  "place": { en: "This is a peaceful place.", tr: "Burası huzurlu bir yer." },
  "here": { en: "Come here, please.", tr: "Lütfen buraya gel." },
  "there": { en: "The keys are over there.", tr: "Anahtarlar şurada." },

  // food
  "water": { en: "Please drink more water.", tr: "Lütfen daha çok su iç." },
  "tea": { en: "She drinks tea every afternoon.", tr: "Her öğleden sonra çay içer." },
  "coffee": { en: "He drinks coffee in the morning.", tr: "Sabahları kahve içer." },
  "milk": { en: "The baby drinks warm milk.", tr: "Bebek ılık süt içer." },
  "juice": { en: "I made fresh orange juice.", tr: "Taze portakal suyu yaptım." },
  "bread": { en: "We buy fresh bread every day.", tr: "Her gün taze ekmek alırız." },
  "rice": { en: "She cooked rice for dinner.", tr: "Akşam yemeği için pirinç pişirdi." },
  "pasta": { en: "The children love pasta.", tr: "Çocuklar makarnayı çok sever." },
  "soup": { en: "This soup is very hot.", tr: "Bu çorba çok sıcak." },
  "salad": { en: "I ordered a fresh salad.", tr: "Taze bir salata sipariş ettim." },
  "meat": { en: "He doesn't eat meat.", tr: "O et yemez." },
  "fish": { en: "We had fish for lunch.", tr: "Öğle yemeğinde balık yedik." },
  "egg": { en: "I boiled an egg this morning.", tr: "Bu sabah bir yumurta haşladım." },
  "cheese": { en: "This cheese is very delicious.", tr: "Bu peynir çok lezzetli." },
  "fruit": { en: "Eat more fruit every day.", tr: "Her gün daha çok meyve ye." },
  "apple": { en: "She ate a red apple.", tr: "Kırmızı bir elma yedi." },
  "banana": { en: "I have a banana for breakfast.", tr: "Kahvaltıda bir muz yerim." },
  "orange": { en: "This orange is very sweet.", tr: "Bu portakal çok tatlı." },
  "lemon": { en: "Add some lemon to the tea.", tr: "Çaya biraz limon ekle." },
  "vegetable": { en: "Every meal has a vegetable.", tr: "Her öğünde bir sebze var." },
  "potato": { en: "We planted potatoes in the garden.", tr: "Bahçeye patates ektik." },
  "tomato": { en: "The salad needs one more tomato.", tr: "Salataya bir domates daha gerek." },
  "cake": { en: "She baked a chocolate cake.", tr: "Çikolatalı bir kek pişirdi." },
  "sugar": { en: "I don't take sugar in my tea.", tr: "Çayıma şeker koymam." },
  "salt": { en: "Please pass the salt.", tr: "Lütfen tuzu uzatır mısın." },
  "snack": { en: "I had a small snack before lunch.", tr: "Öğle yemeğinden önce küçük bir atıştırmalık yedim." },
  "menu": { en: "Can I see the menu, please?", tr: "Menüyü görebilir miyim lütfen?" },
  "restaurant": { en: "We ate at a new restaurant.", tr: "Yeni bir restoranda yemek yedik." },
  "cafe": { en: "Let's meet at the cafe.", tr: "Kafede buluşalım." },
  "bottle": { en: "Fill the bottle with water.", tr: "Şişeyi su ile doldur." },
  "cup": { en: "She poured tea into the cup.", tr: "Fincana çay döktü." },
  "plate": { en: "Put the food on the plate.", tr: "Yemeği tabağa koy." },
  "spoon": { en: "I need a spoon for the soup.", tr: "Çorba için bir kaşığa ihtiyacım var." },
  "fork": { en: "Use a fork to eat the salad.", tr: "Salatayı yemek için çatal kullan." },
  "hungry": { en: "I am very hungry now.", tr: "Şimdi çok açım." },
  "thirsty": { en: "The dog looks thirsty.", tr: "Köpek susamış görünüyor." },
  "delicious": { en: "This soup is delicious.", tr: "Bu çorba çok lezzetli." },
  "hot": { en: "Be careful, the plate is hot.", tr: "Dikkat et, tabak sıcak." },
  "cold": { en: "The coffee is already cold.", tr: "Kahve zaten soğuk." },
  "fresh": { en: "This bread is very fresh.", tr: "Bu ekmek çok taze." },

  // nature
  "sun": { en: "The sun is shining today.", tr: "Bugün güneş parlıyor." },
  "moon": { en: "The moon is bright tonight.", tr: "Bu gece ay parlak." },
  "star": { en: "I saw a star in the sky.", tr: "Gökyüzünde bir yıldız gördüm." },
  "sky": { en: "The sky is very blue today.", tr: "Bugün gökyüzü çok mavi." },
  "cloud": { en: "A big cloud covered the sun.", tr: "Büyük bir bulut güneşi kapladı." },
  "rain": { en: "I love the smell of rain.", tr: "Yağmurun kokusunu severim." },
  "snow": { en: "The children played in the snow.", tr: "Çocuklar karda oynadı." },
  "wind": { en: "The wind is very strong today.", tr: "Bugün rüzgar çok güçlü." },
  "weather": { en: "The weather is perfect for a walk.", tr: "Hava yürüyüş için mükemmel." },
  "tree": { en: "We planted a tree in the yard.", tr: "Bahçeye bir ağaç diktik." },
  "leaf": { en: "A leaf fell from the tree.", tr: "Ağaçtan bir yaprak düştü." },
  "flower": { en: "She gave me a beautiful flower.", tr: "Bana güzel bir çiçek verdi." },
  "seed": { en: "Plant a small seed and watch it rise.", tr: "Küçük bir tohum ek ve büyümesini izle." },
  "grass": { en: "The dog is running on the grass.", tr: "Köpek çimenin üzerinde koşuyor." },
  "soil": { en: "This soil is good for vegetables.", tr: "Bu toprak sebzeler için iyi." },
  "river": { en: "We walked along the river.", tr: "Nehir boyunca yürüdük." },
  "sea": { en: "The house is close to the sea.", tr: "Ev denize yakın." },
  "mountain": { en: "We climbed a small mountain.", tr: "Küçük bir dağa tırmandık." },
  "forest": { en: "There are many trees in the forest.", tr: "Ormanda birçok ağaç var." },
  "animal": { en: "This zoo has many animals.", tr: "Bu hayvanat bahçesinde birçok hayvan var." },
  "dog": { en: "My dog loves to run.", tr: "Köpeğim koşmayı sever." },
  "cat": { en: "The cat is sleeping on the sofa.", tr: "Kedi kanepede uyuyor." },
  "bird": { en: "A bird is singing outside.", tr: "Dışarıda bir kuş şakıyor." },
  "horse": { en: "The farmer has three horses.", tr: "Çiftçinin üç atı var." },
  "cow": { en: "The cow gives fresh milk.", tr: "İnek taze süt verir." },
  "sheep": { en: "The sheep are eating grass.", tr: "Koyunlar çimen yiyor." },
  "green": { en: "She wore a green dress.", tr: "Yeşil bir elbise giydi." },
  "blue": { en: "The sky turned dark blue.", tr: "Gökyüzü koyu maviye döndü." },
  "red": { en: "He drives a red car.", tr: "Kırmızı bir araba kullanıyor." },
  "yellow": { en: "The sunflower is bright yellow.", tr: "Ayçiçeği parlak sarı." },
  "white": { en: "She painted the wall white.", tr: "Duvarı beyaza boyadı." },
  "black": { en: "He wore a black jacket.", tr: "Siyah bir ceket giydi." },
  "brown": { en: "The dog has brown fur.", tr: "Köpeğin kahverengi tüyleri var." },
  "beautiful": { en: "What a beautiful garden!", tr: "Ne güzel bir bahçe!" },
  "clean": { en: "Please keep the kitchen clean.", tr: "Lütfen mutfağı temiz tut." },
  "dry": { en: "The towels are already dry.", tr: "Havlular zaten kuru." },
  "wet": { en: "My shoes are wet from the rain.", tr: "Ayakkabılarım yağmurdan ıslak." },
  "warm": { en: "It's warm outside today.", tr: "Bugün dışarısı ılık." },
  "cool": { en: "The evening air feels cool.", tr: "Akşam havası serin geliyor." },
  "bright": { en: "The room is very bright.", tr: "Oda çok aydınlık." },

  // health_emotions
  "body": { en: "Exercise is good for your body.", tr: "Egzersiz vücuduna iyi gelir." },
  "head": { en: "My head hurts a little.", tr: "Başım biraz ağrıyor." },
  "face": { en: "She has a kind face.", tr: "Onun nazik bir yüzü var." },
  "eye": { en: "He has blue eyes.", tr: "Onun mavi gözleri var." },
  "ear": { en: "My ear feels blocked.", tr: "Kulağım tıkalı hissediyor." },
  "nose": { en: "The baby has a small nose.", tr: "Bebeğin küçük bir burnu var." },
  "mouth": { en: "Open your mouth, please.", tr: "Lütfen ağzını aç." },
  "hand": { en: "She held her son's hand.", tr: "Oğlunun elini tuttu." },
  "arm": { en: "He broke his arm last week.", tr: "Geçen hafta kolunu kırdı." },
  "leg": { en: "My leg hurts after running.", tr: "Koştuktan sonra bacağım ağrıyor." },
  "foot": { en: "I hurt my foot yesterday.", tr: "Dün ayağımı incittim." },
  "heart": { en: "The doctor checked my heart.", tr: "Doktor kalbimi kontrol etti." },
  "health": { en: "Good sleep is important for health.", tr: "İyi uyku sağlık için önemlidir." },
  "medicine": { en: "Take this medicine after meals.", tr: "Bu ilacı yemeklerden sonra al." },
  "hospital": { en: "She works at the city hospital.", tr: "Şehir hastanesinde çalışıyor." },
  "happy": { en: "I am very happy today.", tr: "Bugün çok mutluyum." },
  "sad": { en: "The movie made her sad.", tr: "Film onu üzdü." },
  "tired": { en: "I feel very tired tonight.", tr: "Bu gece çok yorgun hissediyorum." },
  "angry": { en: "He was angry about the delay.", tr: "Gecikmeye kızgındı." },
  "afraid": { en: "She is afraid of spiders.", tr: "Örümceklerden korkuyor." },
  "calm": { en: "Please stay calm.", tr: "Lütfen sakin kal." },
  "quiet": { en: "The garden is very quiet in the morning.", tr: "Bahçe sabahları çok sessizdir." },
  "busy": { en: "I am busy this weekend.", tr: "Bu hafta sonu meşgulüm." },
  "ready": { en: "Are you ready to go?", tr: "Gitmeye hazır mısın?" },
  "well": { en: "She sings very well.", tr: "O çok iyi şarkı söylüyor." },
  "sick": { en: "He stayed home because he was sick.", tr: "Hasta olduğu için evde kaldı." },
  "strong": { en: "He is strong enough to carry it.", tr: "Onu taşıyacak kadar güçlü." },
  "weak": { en: "I felt weak after the flu.", tr: "Gripten sonra kendimi zayıf hissettim." },
  "careful": { en: "Be careful on the wet floor.", tr: "Islak zeminde dikkatli ol." },
  "safe": { en: "This neighborhood feels very safe.", tr: "Bu mahalle çok güvenli hissettiriyor." },
  "help": { en: "Can you help me with this bag?", tr: "Bu çantayla bana yardım edebilir misin?" },
  "smile": { en: "Her smile made everyone happy.", tr: "Onun gülümsemesi herkesi mutlu etti." },
  "love": { en: "They love spending time together.", tr: "Birlikte vakit geçirmeyi severler." },
  "hope": { en: "I hope you feel better soon.", tr: "Umarım yakında iyileşirsin." },
  "sleep": { en: "I need eight hours of sleep.", tr: "Sekiz saat uykuya ihtiyacım var." },
  "rest": { en: "You should rest after work.", tr: "İşten sonra dinlenmelisin." },
  "pain": { en: "She felt pain in her shoulder.", tr: "Omzunda ağrı hissetti." },
  "exercise": { en: "I exercise every morning.", tr: "Her sabah egzersiz yaparım." },
  "healthy": { en: "Eating vegetables keeps you healthy.", tr: "Sebze yemek seni sağlıklı tutar." },
  "fine": { en: "I'm fine, thank you.", tr: "İyiyim, teşekkür ederim." },

  // core_verbs
  "be": { en: "She wants to be a doctor.", tr: "O bir doktor olmak istiyor." },
  "have": { en: "I have two brothers.", tr: "İki erkek kardeşim var." },
  "do": { en: "What do you do on weekends?", tr: "Hafta sonları ne yaparsın?" },
  "go": { en: "We go to school by bus.", tr: "Okula otobüsle gideriz." },
  "come": { en: "Please come to my party.", tr: "Lütfen partime gel." },
  "get": { en: "I get up at seven every day.", tr: "Her gün saat yedide kalkarım." },
  "make": { en: "She makes coffee every morning.", tr: "Her sabah kahve yapar." },
  "take": { en: "Take the bus to the station.", tr: "İstasyona otobüsle git." },
  "give": { en: "Can you give me the salt?", tr: "Bana tuzu verebilir misin?" },
  "put": { en: "Put your books on the table.", tr: "Kitaplarını masaya koy." },
  "keep": { en: "Keep the door closed, please.", tr: "Lütfen kapıyı kapalı tut." },
  "know": { en: "I know the answer to that.", tr: "Onun cevabını biliyorum." },
  "think": { en: "I think it will rain today.", tr: "Bugün yağmur yağacağını düşünüyorum." },
  "want": { en: "Do you want some tea?", tr: "Biraz çay ister misin?" },
  "need": { en: "I need a new phone.", tr: "Yeni bir telefona ihtiyacım var." },
  "like": { en: "I like this song a lot.", tr: "Bu şarkıyı çok seviyorum." },
  "enjoy": { en: "We enjoy walking in the park.", tr: "Parkta yürümekten keyif alırız." },
  "use": { en: "You can use my pen.", tr: "Kalemimi kullanabilirsin." },
  "find": { en: "I can't find my keys.", tr: "Anahtarlarımı bulamıyorum." },
  "look": { en: "Look at that beautiful sunset.", tr: "Şu güzel gün batımına bak." },
  "see": { en: "I can see the mountains from here.", tr: "Buradan dağları görebiliyorum." },
  "watch": { en: "We watch the news every evening.", tr: "Her akşam haberleri izleriz." },
  "hear": { en: "I can hear music outside.", tr: "Dışarıda müzik duyabiliyorum." },
  "listen": { en: "Listen carefully to the teacher.", tr: "Öğretmeni dikkatlice dinle." },
  "say": { en: "What did she say to you?", tr: "Sana ne söyledi?" },
  "speak": { en: "He can speak three languages.", tr: "Üç dil konuşabiliyor." },
  "ask": { en: "You can ask me anything.", tr: "Bana istediğini sorabilirsin." },
  "tell": { en: "Tell me about your day.", tr: "Bana gününü anlat." },
  "read": { en: "I read a book before bed.", tr: "Yatmadan önce bir kitap okurum." },
  "write": { en: "She writes in her diary every night.", tr: "Her gece günlüğüne yazar." },
  "learn": { en: "I want to learn a new language.", tr: "Yeni bir dil öğrenmek istiyorum." },
  "teach": { en: "She teaches math at school.", tr: "Okulda matematik öğretiyor." },
  "study": { en: "He studies every evening.", tr: "Her akşam ders çalışır." },
  "play": { en: "The children play outside after school.", tr: "Çocuklar okuldan sonra dışarıda oynar." },
  "walk": { en: "We walk to work together.", tr: "İşe birlikte yürüyerek gideriz." },
  "run": { en: "She runs every morning in the park.", tr: "Her sabah parkta koşar." },
  "sit": { en: "Please sit down and relax.", tr: "Lütfen otur ve rahatla." },
  "stand": { en: "He stood near the window.", tr: "Pencerenin yanında ayakta durdu." },
  "unlock": { en: "Use this key to unlock the door.", tr: "Kapının kilidini açmak için bu anahtarı kullan." },
  "close": { en: "Please close the window, it's cold.", tr: "Lütfen pencereyi kapat, hava soğuk." },

  // descriptions
  "big": { en: "They live in a big house.", tr: "Büyük bir evde yaşıyorlar." },
  "small": { en: "I bought a small gift for her.", tr: "Ona küçük bir hediye aldım." },
  "long": { en: "It was a long journey.", tr: "Uzun bir yolculuktu." },
  "short": { en: "The meeting was very short.", tr: "Toplantı çok kısaydı." },
  "new": { en: "She bought a new car.", tr: "Yeni bir araba aldı." },
  "old": { en: "This is an old photograph.", tr: "Bu eski bir fotoğraf." },
  "good": { en: "That was a good idea.", tr: "Bu iyi bir fikirdi." },
  "bad": { en: "The weather was bad yesterday.", tr: "Dün hava kötüydü." },
  "easy": { en: "This exercise is quite easy.", tr: "Bu egzersiz oldukça kolay." },
  "difficult": { en: "The exam was very difficult.", tr: "Sınav çok zordu." },
  "fast": { en: "He drives too fast.", tr: "Çok hızlı araba kullanıyor." },
  "slow": { en: "The train was slow today.", tr: "Tren bugün yavaştı." },
  "young": { en: "She is the youngest in her class.", tr: "O sınıfındaki en genç kişi." },
  "full": { en: "The bus was completely full.", tr: "Otobüs tamamen doluydu." },
  "empty": { en: "The bottle is empty now.", tr: "Şişe şimdi boş." },
  "cheap": { en: "This restaurant is cheap and good.", tr: "Bu restoran ucuz ve iyi." },
  "expensive": { en: "That watch is very expensive.", tr: "O saat çok pahalı." },
  "important": { en: "This meeting is very important.", tr: "Bu toplantı çok önemli." },
  "different": { en: "Every city feels different.", tr: "Her şehir farklı hissettiriyor." },
  "same": { en: "We both like the same music.", tr: "İkimiz de aynı müziği seviyoruz." },
  "many": { en: "There are many books on the shelf.", tr: "Rafta birçok kitap var." },
  "few": { en: "Only a few people came.", tr: "Sadece birkaç kişi geldi." },
  "more": { en: "Can I have more tea, please?", tr: "Biraz daha çay alabilir miyim?" },
  "less": { en: "I try to eat less sugar.", tr: "Daha az şeker yemeye çalışıyorum." },
  "all": { en: "All the students passed the exam.", tr: "Tüm öğrenciler sınavı geçti." },
  "every": { en: "I exercise every day.", tr: "Her gün egzersiz yaparım." },
  "some": { en: "Can you give me some water?", tr: "Bana biraz su verebilir misin?" },
  "other": { en: "The other students are still waiting.", tr: "Diğer öğrenciler hâlâ bekliyor." },
  "first": { en: "This is my first visit here.", tr: "Buraya ilk ziyaretim." },
  "last": { en: "This is the last bus tonight.", tr: "Bu, bu geceki son otobüs." },
  "one": { en: "I only need one ticket.", tr: "Sadece bir bilete ihtiyacım var." },
  "two": { en: "She has two brothers.", tr: "İki erkek kardeşi var." },
  "three": { en: "We waited for three hours.", tr: "Üç saat bekledik." },
  "four": { en: "The table has four chairs.", tr: "Masanın dört sandalyesi var." },
  "five": { en: "The store closes in five minutes.", tr: "Mağaza beş dakika içinde kapanıyor." },
  "six": { en: "I wake up at six every day.", tr: "Her gün saat altıda uyanırım." },
  "seven": { en: "There are seven days in a week.", tr: "Bir haftada yedi gün var." },
  "eight": { en: "The film starts at eight.", tr: "Film saat sekizde başlıyor." },
  "nine": { en: "School starts at nine.", tr: "Okul saat dokuzda başlıyor." },
  "ten": { en: "I counted to ten.", tr: "Ona kadar saydım." },
};
