import { StyleSheet } from "react-native";
import { C, radius } from "../../../theme/colors";

export const S = StyleSheet.create({
  card: {
    backgroundColor: C.surface,
    borderRadius: radius.lg || 18,
    borderWidth: 1,
    borderColor: C.line,
    padding: 16,
    gap: 12,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconCircleGuest: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: C.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  iconCircleUser: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: C.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  copy: {
    flex: 1,
    gap: 2,
  },
  title: {
    color: C.ink,
    fontSize: 15.5,
    fontWeight: "700",
  },
  subtitle: {
    color: C.muted,
    fontSize: 12.5,
    lineHeight: 16,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  userName: {
    color: C.ink,
    fontSize: 15.5,
    fontWeight: "700",
  },
  userEmail: {
    color: C.muted,
    fontSize: 13,
  },
  verifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: C.successSoft,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radius.xs || 8,
  },
  verifiedBadgeTxt: {
    color: C.successText,
    fontSize: 10,
    fontWeight: "700",
  },
  unverifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: C.attentionSoft,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radius.xs || 8,
  },
  unverifiedBadgeTxt: {
    color: C.attentionText,
    fontSize: 10,
    fontWeight: "700",
  },
  authBtn: {
    minHeight: 46,
    backgroundColor: C.reward,
    borderRadius: radius.button || 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 16,
  },
  authBtnTxt: {
    color: C.ink,
    fontSize: 14.5,
    fontWeight: "700",
  },
  noticeBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: C.primarySoft,
    padding: 10,
    borderRadius: radius.md || 12,
  },
  noticeTxt: {
    color: C.primary,
    fontSize: 12,
    fontWeight: "600",
    flex: 1,
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  subBtn: {
    minHeight: 38,
    backgroundColor: C.primarySoft,
    borderWidth: 1,
    borderColor: C.primaryBorder,
    borderRadius: radius.md || 12,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  subBtnTxt: {
    color: C.primary,
    fontSize: 12.5,
    fontWeight: "700",
  },
  logoutBtn: {
    minHeight: 38,
    backgroundColor: C.lineSoft,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: radius.md || 12,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  logoutBtnTxt: {
    color: C.ink,
    fontSize: 12.5,
    fontWeight: "600",
  },
  deleteBtn: {
    alignSelf: "center",
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  deleteBtnTxt: {
    color: C.attentionText,
    fontSize: 12,
    fontWeight: "600",
  },
  namePressable: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  editNameBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
  },
  nameInput: {
    flex: 1,
    height: 34,
    borderWidth: 1,
    borderColor: C.primary,
    borderRadius: radius.sm || 8,
    paddingHorizontal: 8,
    fontSize: 14,
    color: C.ink,
    backgroundColor: C.canvas,
  },
  saveNameBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: C.canvas,
    padding: 8,
    borderRadius: radius.md || 12,
  },
  avatarLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: C.muted,
  },
  avatarList: {
    flexDirection: "row",
    gap: 6,
  },
  avatarBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarBtnActive: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
});
